/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ohyh335Vuwt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"

export function Sidebar-and-Chat() {
  return (
    <div className="grid md:grid-cols-[260px_1fr] min-h-screen w-full">
      <div className="bg-neutral-950 hidden md:flex flex-col gap-2 text-white">
        <div className="sticky top-0 p-2">
          <Button
            className="w-full text-left px-2 justify-start p hover:bg-neutral-900 hover:text-neutral-50 gap-2"
            variant="ghost"
          >
            <div className="rounded-full bg-white text-black flex items-center justify-center w-7 h-7">
              <BotIcon className="h-4 w-4" />
            </div>
            <div className="grow text-ellipsis overflow-hidden whitespace-nowrap text-sm">Arvin</div>
            <PenIcon className="h-4 w-4" />
          </Button>
        </div>
        <div className="overflow-auto flex-1">
          <div className="grid gap-1 p-2">
            <div className="text-stone-500 text-xs font-medium px-2">Integrated Accounts</div>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block bg-neutral-900 hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <MailIcon className="h-4 w-4 mr-2" />
              Gmail
            </Link>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <CalendarIcon className="h-4 w-4 mr-2" />
              Calendar
            </Link>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <TrelloIcon className="h-4 w-4 mr-2" />
              Trello
            </Link>
          </div>
          <div className="grid gap-1 p-2">
            <div className="text-stone-500 text-xs font-medium px-2">Recent Conversations</div>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <WebcamIcon className="h-4 w-4 mr-2" />
              Summarize latest emails
            </Link>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <CalendarCheckIcon className="h-4 w-4 mr-2" />
              Schedule meeting
            </Link>
            <Link
              className="truncate overflow-hidden flex-1 text-sm transition-colors rounded-md whitespace-nowrap p-2 block hover:bg-neutral-900 hover:text-neutral-50"
              href="#"
            >
              <ClipboardIcon className="h-4 w-4 mr-2" />
              Create new todo
            </Link>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <div className="sticky top-0 bg-white dark:bg-gray-950 p-2 border-b border-gray-200 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Button className="rounded-full hover:bg-gray-100 dark:hover:bg-gray-800" size="icon" variant="ghost">
                <MenuIcon className="h-5 w-5" />
              </Button>
              <div className="font-semibold">Arvin</div>
            </div>
            <div className="flex items-center gap-2">
              <Button className="rounded-full hover:bg-gray-100 dark:hover:bg-gray-800" size="icon" variant="ghost">
                <ViewIcon className="h-5 w-5" />
                <span className="sr-only">Summarize Emails</span>
              </Button>
              <Button className="rounded-full hover:bg-gray-100 dark:hover:bg-gray-800" size="icon" variant="ghost">
                <TimerIcon className="h-5 w-5" />
                <span className="sr-only">Create Todo</span>
              </Button>
              <Button className="rounded-full hover:bg-gray-100 dark:hover:bg-gray-800" size="icon" variant="ghost">
                <CalendarIcon className="h-5 w-5" />
                <span className="sr-only">Schedule Event</span>
              </Button>
            </div>
          </div>
        </div>
        <div className="flex-1 overflow-auto">
          <div className="max-w-2xl mx-auto flex flex-col items-start gap-8 px-4 py-8">
            <div className="flex items-start gap-4">
              <Avatar className="border w-8 h-8">
                <AvatarImage alt="Image" src="/placeholder-user.jpg" />
                <AvatarFallback>YO</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-bold">You</div>
                <div className="prose prose-stone">
                  <p>Hi Arvin, can you please summarize the key points from my latest emails?</p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="border w-8 h-8">
                <AvatarImage alt="Image" src="/placeholder-avatar.jpg" />
                <AvatarFallback>AR</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-bold">Arvin</div>
                <div className="prose prose-stone">
                  <p>Sure, I'd be happy to summarize your latest emails. Let me take a look...</p>
                  <p>
                    The key points are:
                    <ul>
                      <li>Your client has requested a meeting to discuss the project timeline and budget</li>
                      <li>Your team lead has sent an update on the new feature development</li>
                      <li>Your manager has asked you to prepare a presentation for the quarterly review</li>
                    </ul>
                  </p>
                  <p>
                    Would you like me to schedule the client meeting, update the team on the new feature, or prepare the
                    quarterly review presentation?
                  </p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="border w-8 h-8">
                <AvatarImage alt="Image" src="/placeholder-user.jpg" />
                <AvatarFallback>YO</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-bold">You</div>
                <div className="prose prose-stone">
                  <p>
                    That's great, Arvin. Could you please schedule the client meeting and update the team on the new
                    feature? I'll handle the quarterly review presentation.
                  </p>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="border w-8 h-8">
                <AvatarImage alt="Image" src="/placeholder-avatar.jpg" />
                <AvatarFallback>AR</AvatarFallback>
              </Avatar>
              <div className="grid gap-1">
                <div className="font-bold">Arvin</div>
                <div className="prose prose-stone">
                  <p>
                    Absolutely, I've scheduled the client meeting for 3pm on Friday and sent an update to the team on
                    the new feature development. Let me know if you need anything else!
                  </p>
                </div>
                <div className="flex items-center gap-2 py-2">
                  <Button
                    className="w-4 h-4 hover:bg-transparent text-stone-400 hover:text-stone-900"
                    size="icon"
                    variant="ghost"
                  >
                    <ClipboardIcon className="w-4 h-4" />
                    <span className="sr-only">Copy</span>
                  </Button>
                  <Button
                    className="w-4 h-4 hover:bg-transparent text-stone-400 hover:text-stone-900"
                    size="icon"
                    variant="ghost"
                  >
                    <ThumbsUpIcon className="w-4 h-4" />
                    <span className="sr-only">Upvote</span>
                  </Button>
                  <Button
                    className="w-4 h-4 hover:bg-transparent text-stone-400 hover:text-stone-900"
                    size="icon"
                    variant="ghost"
                  >
                    <ThumbsDownIcon className="w-4 h-4" />
                    <span className="sr-only">Downvote</span>
                  </Button>
                  <Button
                    className="w-4 h-4 hover:bg-transparent text-stone-400 hover:text-stone-900"
                    size="icon"
                    variant="ghost"
                  >
                    <RefreshCcwIcon className="w-4 h-4" />
                    <span className="sr-only">Regenerate</span>
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="max-w-2xl w-full sticky bottom-0 mx-auto py-2 flex flex-col gap-1.5 px-4 bg-white dark:bg-gray-950">
          <div className="relative">
            <Textarea
              className="min-h-[48px] rounded-2xl resize-none p-4 border border-gray-200 border-neutral-400 shadow-sm pr-16 dark:border-gray-800 dark:border-gray-800"
              id="message"
              name="message"
              placeholder="Message Arvin..."
              rows={1}
            />
            <Button className="absolute top-3 right-3 w-8 h-8" disabled size="icon" type="submit">
              <ArrowUpIcon className="w-4 h-4" />
              <span className="sr-only">Send</span>
            </Button>
          </div>
          <p className="text-xs text-center text-neutral-700 font-medium">
            Arvin is an AI assistant. Consider verifying important information.
          </p>
        </div>
      </div>
    </div>
  )
}

function ArrowUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function BotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function CalendarCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="m9 16 2 2 4-4" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClipboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
    </svg>
  )
}


function RefreshCcwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
      <path d="M16 16h5v5" />
    </svg>
  )
}


function ThumbsDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 14V2" />
      <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22h0a3.13 3.13 0 0 1-3-3.88Z" />
    </svg>
  )
}


function ThumbsUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}


function TimerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="10" x2="14" y1="2" y2="2" />
      <line x1="12" x2="15" y1="14" y2="11" />
      <circle cx="12" cy="14" r="8" />
    </svg>
  )
}


function TrelloIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <rect width="3" height="9" x="7" y="7" />
      <rect width="3" height="5" x="14" y="7" />
    </svg>
  )
}


function ViewIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z" />
      <path d="M12 13a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
      <path d="M21 17v2a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-2" />
      <path d="M21 7V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2" />
    </svg>
  )
}


function WebcamIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>
  )
}
